apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-app-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "my-app-role"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-config.txt: "secret/data/my-app/config"
        vault.hashicorp.com/agent-inject-template-config.txt: |
          {{- with secret "secret/data/my-app/config" -}}
          DB_USER={{ .Data.data.username }}
          DB_PASS={{ .Data.data.password }}
          {{- end }}
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            request:
              memory: "128Mi"
              cpu: "500m"
          args:
            - |
              echo "Starting app...";
              echo "Loaded secrets:"; cat /vault/secrets/config.txt;
              sleep 3600
          volumeMounts:
            - name: vault-secret
              mountPath: /vault/secrets
              readOnly: true
      volumes:
        - name: vault-secret
          emptyDir: {}
