apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "application.name" . }}-crt
  namespace: {{ include "application.namespace" . }}
spec:
  secretName: {{ include "application.name" . }}-tls
  dnsNames:
    - {{ .Values.domain }}
  duration: 8760h
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer
