apiVersion: v1
kind: Service
metadata:
  name: {{ include "application.name" . }}-svc
  namespace: {{ include "application.namespace" . }}
spec:
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.deployment.container.port}}
  selector:
    app: {{ include "application.name" . }}
  type: {{ .Values.service.type}}
